source 'https://github.com/CocoaPods/Specs.git'
source 'https://gitee.com/padding/YQPods.git'

use_frameworks!
platform :ios, '9.0'

target 'YQAudioTool_Example' do
  pod 'YQAudioTool', :path => '../'

  #pod 'Moya/RxSwift', '~> 12.0'
  #pod 'SnapKit', '~> 4.0.0'
  #pod 'RxCoreData', '~> 0.5.1'
  #pod 'RxDataSources', '~> 3.0'

  target 'YQAudioTool_Tests' do
    inherit! :search_paths

    
  end
end
